# config.yaml

genotype_prefix: "geno_EUR_SCZ"
weights_type: "EQTL"
genotype_file_path: "/Users/davidenoma/Desktop/PhD._BMB/LONG_LAB/Projects/Stability of kernel based methods/"
weights_file: "/Users/davidenoma/Desktop/PhD._BMB/LONG_LAB/Projects/Stability of kernel based methods/eqtl_weights.csv"
gene_regions_file: /path/to/gene_regions_file
disgenet_reference_file: /path/to/ref_file