# config.yaml
#Replace with your configuration
genotype_prefix: ""
weights_type: ""
genotype_file_path: "genotype_data/"
#Your weights file must follow te format of the sample
weights_file: "weights/weights.csv"
gene_regions_file: "helper/gene_regions.csv"
disgenet_reference_file: "disease_database/{}.tsv"
plink_path: ""
sample_size: 2414
